### ISSUE TITLE
classificationReport and confusionMatrix explanation are not returned in sensor anomaly case

### ISSUE THREAD

**Issue by anneliret** [isee4xai/iSeeIssueTracker#12]
the use case (Sensor Anomaly Detection (Bosch) v237 ) is complete, published. but the chatbot does not return any explanation (not calling the classificationReport, confusionMatrix explainer ?) to any of the question with the ML engineer persona.
![image](https://github.com/isee4xai/iSeeIssueTracker/assets/91963804/bda3e717-bfbe-4ec1-85fc-7b17d4accd48)

the other persona (Auditor) works (with gradients and nearest neighbours)

**Comment by anjanaw** [comment]
Fixed the Transparency intent. it should work as expected now. Issue was it has not retrieved strategies since we did some fixes last week. 

Performance intent had a strategy that is invalid. two sibling Explainer nodes can only have Supplement, Complement, Variant or Replacement parents. Not Sequence or Priority parents. 
<img width="741" alt="Screenshot 2024-02-14 at 16 42 37" src="https://github.com/isee4xai/iSeeIssueTracker/assets/233262/73dabc82-e4de-459d-acb5-5db3bc5e9395">

Performance intent still returns an issue with the cases are retrieved. Will investigate and update.

**Comment by anjanaw** [comment]
Performance intent now retrieve cases successfully. 
I have created the intent and retrieved and selected the strategy. 
Please add evaluation questions to complete the intent. Then it should be ready for testing (assuming other parts of the use case are complete)
