### ISSUE TITLE
Strategy dissapearing and update message when opening tab

### ISSUE THREAD

**Issue by martcaro** [isee4xai/iSeeIssueTracker#9]
Hey guys, just found a bug on the cockpit after retrieving explanation strategies. See the screenshot.  I opened the cockpit, later the bt editor to edit the second strategy. I close that, and when I came back to the cockpit I ssw the first strategy had dissapeared. 
Also, each time that i changed the tab (not the bt editor necessarily) an update message appears. Here i changed the tab three times, and there you go. 
![Captura de pantalla 2024-02-13 120351](https://github.com/isee4xai/iSeeIssueTracker/assets/18444486/8bec651f-5203-498b-8556-2f15b388f815)

**Comment by anjanaw** [comment]
Add warning when they press "edit".
Update waiting message to say "stay in this tab until complete".

**Comment by anjanaw** [comment]
Warning message added before leaving the cockpit. 
Updated loading warning message to say "stay in the page until the process is complete". 

Multiple loadings are disabled. However, issue still exist in the following scenario

1. User opens the editor from the cockpit
2. Returns to cockpit without saving changes to the tree 
3. Cockpit get refreshed (no changes)
4. User goes back to the previously opened editor and make changes and save
5. Returns to the cockpit - not loading changes because its restricted to once

In this case, user will have to retrieve strategies again.
